name: CI

on:
  pull_request:
    branches: [ main, release-* ]

jobs:
  build-and-test :
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app

    - name: Set environment variables from project settings
      run: |
        exec .github/scripts/set-env-from-xcodeproj.sh

    - name: Build and test
      run: xcodebuild clean build test -project "$PRODUCT_NAME.xcodeproj" -scheme "$PRODUCT_NAME" -destination "platform=iOS Simulator,name=iPhone 13,OS=16.2" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO -quiet
